import type {Lang} from './problems'
export type Lesson={id:string;title:string;track:string;level:string;intro:Record<Lang,string>;code:string;takeaway:Record<Lang,string>;challenge:string}
export const lessons:Lesson[]=[
{id:'variables',title:'Variables & values',track:'Foundations',level:'01',intro:{en:'Variables give names to values. Prefer const by default, and let when a value changes. JavaScript has strings, numbers, booleans, objects and more.',el:'Οι μεταβλητές δίνουν ονόματα στις τιμές. Προτίμησε const και χρησιμοποίησε let όταν η τιμή αλλάζει. Η JavaScript διαθέτει strings, αριθμούς, booleans, objects και άλλους τύπους.'},code:'const name = "Ada";\nlet score = 0;\nscore += 10;\nconsole.log(`${name}: ${score}`);',takeaway:{en:'Try changing score and run the code in Playground.',el:'Δοκίμασε να αλλάξεις το score και εκτέλεσε τον κώδικα στο Playground.'},challenge:'sum-two'},
{id:'conditionals',title:'Conditions & decisions',track:'Foundations',level:'02',intro:{en:'Use if, else and comparison operators to choose what happens next. === compares values without type coercion.',el:'Με if, else και τελεστές σύγκρισης αποφασίζεις τι θα συμβεί. Το === συγκρίνει χωρίς μετατροπή τύπων.'},code:'const age = 20;\nif (age >= 18) {\n  console.log("Adult");\n} else {\n  console.log("Minor");\n}',takeaway:{en:'Consider edge cases at 17 and 18.',el:'Δοκίμασε τις οριακές περιπτώσεις 17 και 18.'},challenge:'fizzbuzz'},
{id:'loops',title:'Loops that make sense',track:'Foundations',level:'03',intro:{en:'Loops repeat work. Use for when you need an index, or for...of to iterate values.',el:'Οι βρόχοι επαναλαμβάνουν ενέργειες. Χρησιμοποίησε for για δείκτες ή for...of για τιμές.'},code:'let total = 0;\nfor (const value of [2, 4, 6]) {\n  total += value;\n}\nconsole.log(total);',takeaway:{en:'Think about the initial value for an empty array.',el:'Σκέψου την αρχική τιμή για έναν κενό πίνακα.'},challenge:'array-sum'},
{id:'functions',title:'Functions & return',track:'Functions',level:'04',intro:{en:'Functions package repeatable logic. Parameters are inputs; return provides the output. A function that only logs does not return that logged value.',el:'Οι συναρτήσεις οργανώνουν επαναχρησιμοποιήσιμη λογική. Οι παράμετροι είναι είσοδοι και το return δίνει αποτέλεσμα. Το console.log δεν είναι το ίδιο με το return.'},code:'function square(number) {\n  return number * number;\n}\nconsole.log(square(5));',takeaway:{en:'Try pure functions that do not change external variables.',el:'Δοκίμασε καθαρές συναρτήσεις που δεν αλλάζουν εξωτερικές μεταβλητές.'},challenge:'factorial'},
{id:'arrays',title:'Working with arrays',track:'Collections',level:'05',intro:{en:'Arrays store ordered values. map transforms each item; filter keeps items that match a condition; reduce combines items.',el:'Οι πίνακες αποθηκεύουν τιμές με σειρά. Το map μετασχηματίζει, το filter επιλέγει και το reduce συνδυάζει στοιχεία.'},code:'const nums = [1, 2, 3, 4];\nconsole.log(nums.filter(n => n % 2 === 0));\nconsole.log(nums.map(n => n * 2));',takeaway:{en:'These methods return new arrays without mutating the input.',el:'Οι μέθοδοι επιστρέφουν νέους πίνακες χωρίς να αλλάζουν τον αρχικό.'},challenge:'even-numbers'},
{id:'objects',title:'Objects, Map & Set',track:'Collections',level:'06',intro:{en:'Objects store named properties, Map maps keys to values, and Set stores unique values.',el:'Τα objects αποθηκεύουν ιδιότητες, το Map συνδέει κλειδιά με τιμές και το Set κρατά μοναδικά στοιχεία.'},code:'const counts = new Map();\nfor (const letter of "banana") {\n  counts.set(letter, (counts.get(letter) || 0) + 1);\n}\nconsole.log([...counts]);',takeaway:{en:'Compare Map with plain objects for dynamic keys.',el:'Σύγκρινε το Map με απλά objects για δυναμικά κλειδιά.'},challenge:'frequency-map'},
{id:'recursion',title:'Understanding recursion',track:'Algorithms',level:'07',intro:{en:'A recursive function calls itself to solve a smaller version of the problem. Every recursion requires a base case.',el:'Μια αναδρομική συνάρτηση καλεί τον εαυτό της για μικρότερο υποπρόβλημα. Πάντα χρειάζεται συνθήκη τερματισμού.'},code:'function countdown(n) {\n  if (n <= 0) return;\n  console.log(n);\n  countdown(n - 1);\n}\ncountdown(3);',takeaway:{en:'Missing the base case may cause a stack overflow.',el:'Χωρίς συνθήκη τερματισμού μπορεί να προκύψει stack overflow.'},challenge:'flatten-deep'},
{id:'complexity',title:'Big O essentials',track:'Algorithms',level:'08',intro:{en:'Big O describes how resource use grows with input size. One pass is often O(n); nested full loops often O(n²). Binary search on sorted data is O(log n).',el:'Το Big O περιγράφει πώς αυξάνεται το κόστος με το μέγεθος εισόδου. Μία διέλευση είναι συχνά O(n), δύο εμφωλευμένοι βρόχοι O(n²), ενώ η δυαδική αναζήτηση O(log n).'},code:'function findIndex(nums, target) {\n  for (let i = 0; i < nums.length; i++) {\n    if (nums[i] === target) return i;\n  }\n  return -1;\n}\nconsole.log(findIndex([2,4,6], 4));',takeaway:{en:'Analyze worst-case steps, not just real-time milliseconds.',el:'Μελέτησε τα βήματα στη χειρότερη περίπτωση, όχι μόνο τα milliseconds.'},challenge:'binary-search'}]
