import type {Problem} from './problems'
const mk=(id:string,title:string,level:Problem['level'],category:string,en:string,el:string,example:string,hintEn:string,hintEl:string,args:string,tests:Problem['tests']):Problem=>({id,title,level,category,description:{en,el},example,hint:{en:hintEn,el:hintEl},starter:`function solve(${args}) {\n  // Write your solution here\n}`,tests})
export const additional:Problem[]=[
mk('count-vowels','Count Vowels','Easy','Strings','Count vowels (a,e,i,o,u) in the string, ignoring case.','Μέτρησε τα φωνήεντα (a,e,i,o,u) στο κείμενο, χωρίς διάκριση πεζών και κεφαλαίων.','solve("Hello") → 2','Use a loop and a set of vowels.','Χρησιμοποίησε loop και σύνολο φωνηέντων.','text',[{args:['Hello'],expected:2},{args:['XYZ'],expected:0},{args:['AEIOU'],expected:5}]),
mk('even-numbers','Filter Even Numbers','Easy','Arrays','Return a new array containing only even numbers.','Επίστρεψε νέο πίνακα που περιέχει μόνο ζυγούς αριθμούς.','solve([1,2,3,4]) → [2,4]','Use filter with modulo.','Χρησιμοποίησε filter και modulo.','nums',[{args:[[1,2,3,4]],expected:[2,4]},{args:[[1,3]],expected:[]},{args:[[0,-2,5]],expected:[0,-2]}]),
mk('factorial','Factorial','Easy','Loops','Return n factorial for a non-negative integer.','Υπολόγισε το παραγοντικό μη αρνητικού ακεραίου n.','solve(5) → 120','Start with 1, multiply numbers through n.','Ξεκίνα από 1 και πολλαπλασίασε έως το n.','n',[{args:[0],expected:1},{args:[5],expected:120},{args:[3],expected:6}]),
mk('array-sum','Array Sum','Easy','Arrays','Return the sum of all numbers in the array.','Επίστρεψε το άθροισμα των αριθμών του πίνακα.','solve([1,2,3]) → 6','Use reduce with initial value zero.','Χρησιμοποίησε reduce με αρχική τιμή μηδέν.','nums',[{args:[[1,2,3]],expected:6},{args:[[]],expected:0},{args:[[-2,5]],expected:3}]),
mk('is-prime','Prime Checker','Easy','Loops','Return true if n is prime, else false.','Επίστρεψε true εάν ο n είναι πρώτος αριθμός.','solve(7) → true','Check divisors only up to sqrt(n).','Έλεγξε διαιρέτες μέχρι τη ρίζα του n.','n',[{args:[7],expected:true},{args:[1],expected:false},{args:[9],expected:false},{args:[2],expected:true}]),
mk('capitalize','Capitalize Words','Easy','Strings','Capitalize the first letter of each space-separated word and lowercase the rest.','Κάνε κεφαλαίο το πρώτο γράμμα κάθε λέξης και πεζά τα υπόλοιπα.','solve("hELLO world") → "Hello World"','Split by spaces and map over words.','Χώρισε το κείμενο στα κενά και επεξεργάσου κάθε λέξη.','text',[{args:['hELLO world'],expected:'Hello World'},{args:['javaScript'],expected:'Javascript'}]),
mk('average','Average Value','Easy','Arrays','Return arithmetic mean of a nonempty numeric array.','Επίστρεψε τον μέσο όρο ενός μη κενού πίνακα αριθμών.','solve([2,4,6]) → 4','Divide sum by length.','Διαίρεσε το άθροισμα με το πλήθος.','nums',[{args:[[2,4,6]],expected:4},{args:[[1,2]],expected:1.5}]),
mk('repeat','Repeat Text','Easy','Functions','Return text repeated n times. n is nonnegative.','Επίστρεψε το κείμενο επαναλαμβανόμενο n φορές.','solve("ab",3) → "ababab"','Use repeat method.','Χρησιμοποίησε repeat.','text, n',[{args:['ab',3],expected:'ababab'},{args:['x',0],expected:''}]),
mk('flatten-one','Flatten One Level','Medium','Arrays','Flatten one nesting level from an array of arrays.','Αφαίρεσε ένα επίπεδο εμφώλευσης από πίνακα πινάκων.','solve([[1,2],[3]]) → [1,2,3]','Use flat(1).','Χρησιμοποίησε flat(1).','arrays',[{args:[[[1,2],[3]]],expected:[1,2,3]},{args:[[[],[4]]],expected:[4]}]),
mk('frequency-map','Character Frequencies','Medium','Objects','Return an object mapping each character to its occurrence count.','Επίστρεψε αντικείμενο με πλήθος εμφανίσεων για κάθε χαρακτήρα.','solve("aba") → {a:2,b:1}','Accumulate counts in an object.','Συγκέντρωσε μετρήσεις σε αντικείμενο.','text',[{args:['aba'],expected:{a:2,b:1}},{args:[''],expected:{}}]),
mk('chunk-array','Chunk an Array','Medium','Arrays','Split an array into consecutive arrays of size n (n > 0).','Χώρισε τον πίνακα σε διαδοχικούς υποπίνακες μεγέθους n (n > 0).','solve([1,2,3,4,5],2) → [[1,2],[3,4],[5]]','Slice blocks in a loop.','Κόψε ομάδες με slice σε βρόχο.','nums, n',[{args:[[1,2,3,4,5],2],expected:[[1,2],[3,4],[5]]},{args:[[],3],expected:[]}]),
mk('intersection','Array Intersection','Medium','Sets','Return distinct values shared by both arrays in order of first appearance in array a.','Επίστρεψε μοναδικά κοινά στοιχεία με σειρά εμφάνισης στον πρώτο πίνακα.','solve([1,2,2,3],[2,3]) → [2,3]','Combine Set membership with filtering.','Συνδύασε Set και φιλτράρισμα.','a, b',[{args:[[1,2,2,3],[2,3]],expected:[2,3]},{args:[[1,2],[4]],expected:[]}]),
mk('binary-search','Binary Search','Medium','Searching','Return the index of target in a sorted ascending array, or -1 if missing.','Βρες τον δείκτη του target σε ταξινομημένο πίνακα ή επέστρεψε -1.','solve([1,3,5,7],5) → 2','Reduce search interval by half.','Μείωνε κάθε φορά το εύρος αναζήτησης στο μισό.','nums, target',[{args:[[1,3,5,7],5],expected:2},{args:[[1,3,5],2],expected:-1}]),
mk('merge-sorted','Merge Sorted Arrays','Medium','Sorting','Merge two sorted ascending arrays into one sorted ascending array.','Συγχώνευσε δύο ταξινομημένους πίνακες σε έναν ταξινομημένο πίνακα.','solve([1,3],[2,4]) → [1,2,3,4]','Use two pointers.','Χρησιμοποίησε δύο δείκτες.','a, b',[{args:[[1,3],[2,4]],expected:[1,2,3,4]},{args:[[],[2]],expected:[2]}]),
mk('anagram','Anagram Check','Medium','Strings','Return true if strings contain identical character counts, case sensitive.','Επίστρεψε true εάν δύο κείμενα έχουν τους ίδιους χαρακτήρες και συχνότητες, με διάκριση πεζών.','solve("listen","silent") → true','Sort characters or count frequencies.','Ταξινόμησε τους χαρακτήρες ή μέτρησε τις συχνότητες.','a, b',[{args:['listen','silent'],expected:true},{args:['cat','dog'],expected:false}]),
mk('flatten-deep','Deep Flatten','Medium','Recursion','Recursively flatten a nested array of numbers into a flat array.','Μετέτρεψε αναδρομικά έναν εμφωλευμένο πίνακα αριθμών σε επίπεδο πίνακα.','solve([1,[2,[3]]]) → [1,2,3]','Think recursion or flat(Infinity).','Σκέψου αναδρομή ή flat(Infinity).','nums',[{args:[[1,[2,[3]]]],expected:[1,2,3]},{args:[[]],expected:[]}]),
mk('rotate-array','Rotate Right','Medium','Arrays','Rotate array elements right by k positions.','Μετακίνησε κυκλικά τα στοιχεία του πίνακα δεξιά κατά k θέσεις.','solve([1,2,3,4],1) → [4,1,2,3]','Normalize k by length.','Χρησιμοποίησε modulo για το k.','nums, k',[{args:[[1,2,3,4],1],expected:[4,1,2,3]},{args:[[1,2,3],4],expected:[3,1,2]}]),
mk('fibonacci','Fibonacci Sequence','Medium','Recursion','Return the nth Fibonacci number where F(0)=0 and F(1)=1.','Επίστρεψε τον n-οστό αριθμό Fibonacci, με F(0)=0 και F(1)=1.','solve(7) → 13','Try an iterative dynamic approach.','Δοκίμασε επαναληπτική δυναμική μέθοδο.','n',[{args:[0],expected:0},{args:[7],expected:13},{args:[10],expected:55}]),
mk('longest-unique','Longest Unique Substring','Hard','Algorithms','Return length of longest substring with no duplicate characters.','Επίστρεψε το μήκος της μεγαλύτερης υποσυμβολοσειράς χωρίς επαναλαμβανόμενους χαρακτήρες.','solve("abcabcbb") → 3','Keep a sliding window and last seen positions.','Διατήρησε κυλιόμενο παράθυρο και θέσεις χαρακτήρων.','text',[{args:['abcabcbb'],expected:3},{args:['bbbbb'],expected:1},{args:[''],expected:0}]),
mk('max-subarray','Maximum Subarray Sum','Hard','Algorithms','Find maximum sum of any nonempty contiguous subarray.','Βρες το μέγιστο άθροισμα μη κενού συνεχόμενου υποπίνακα.','solve([-2,1,-3,4,-1,2,1,-5,4]) → 6','Kadane’s algorithm maintains current and best sums.','Ο αλγόριθμος Kadane κρατά τρέχον και μέγιστο άθροισμα.','nums',[{args:[[-2,1,-3,4,-1,2,1,-5,4]],expected:6},{args:[[-3,-1,-2]],expected:-1}]),
mk('coin-change','Coin Change','Hard','Algorithms','Return fewest coins to make amount, or -1 if impossible. Coins are positive integers.','Βρες το ελάχιστο πλήθος κερμάτων για το ποσό ή -1 αν δεν γίνεται.','solve([1,2,5],11) → 3','Build a dynamic programming table.','Χτίσε πίνακα δυναμικού προγραμματισμού.','coins, amount',[{args:[[1,2,5],11],expected:3},{args:[[2],3],expected:-1},{args:[[1],0],expected:0}]),
mk('valid-paths','Grid Paths','Hard','Algorithms','Count unique routes from top-left to bottom-right in an m×n grid, moving only right or down.','Μέτρησε τις διαδρομές από επάνω αριστερά προς κάτω δεξιά σε πλέγμα m×n, μόνο δεξιά ή κάτω.','solve(3,3) → 6','Use a dynamic programming grid.','Χρησιμοποίησε πίνακα δυναμικού προγραμματισμού.','m, n',[{args:[3,3],expected:6},{args:[1,5],expected:1}])
]
