export type Lang = 'el'|'en'
export type Problem = {id:string,title:string,level:'Easy'|'Medium'|'Hard',category:string,description:Record<Lang,string>,example:string,hint:Record<Lang,string>,starter:string,tests:{args:unknown[],expected:unknown}[]}
export const problems:Problem[]=[
{id:'sum-two',title:'Sum Two Numbers',level:'Easy',category:'Fundamentals',description:{en:'Return the sum of two numbers a and b.',el:'Επίστρεψε το άθροισμα δύο αριθμών a και b.'},example:'solve(2, 3) → 5',hint:{en:'Use the + operator.',el:'Χρησιμοποίησε τον τελεστή +.'},starter:'function solve(a, b) {\n  // Your code here\n}',tests:[{args:[2,3],expected:5},{args:[-4,9],expected:5},{args:[0,0],expected:0}]},
{id:'reverse-string',title:'Reverse a String',level:'Easy',category:'Strings',description:{en:'Return the input string in reverse order.',el:'Επίστρεψε το κείμενο με αντίστροφη σειρά χαρακτήρων.'},example:'solve("hello") → "olleh"',hint:{en:'Try split, reverse and join.',el:'Δοκίμασε split, reverse και join.'},starter:'function solve(text) {\n  // Your code here\n}',tests:[{args:['hello'],expected:'olleh'},{args:[''],expected:''},{args:['abc'],expected:'cba'}]},
{id:'max-array',title:'Maximum Value',level:'Easy',category:'Arrays',description:{en:'Return the largest number in a non-empty array.',el:'Βρες τον μεγαλύτερο αριθμό σε έναν μη κενό πίνακα.'},example:'solve([1, 9, 3]) → 9',hint:{en:'Math.max accepts spread arguments.',el:'Η Math.max δέχεται spread arguments.'},starter:'function solve(nums) {\n  // Your code here\n}',tests:[{args:[[1,9,3]],expected:9},{args:[[-4,-9,-1]],expected:-1},{args:[[7]],expected:7}]},
{id:'palindrome',title:'Palindrome Check',level:'Easy',category:'Strings',description:{en:'Return true when a string reads identically backwards (case sensitive).',el:'Επίστρεψε true όταν το κείμενο διαβάζεται το ίδιο ανάποδα (με διάκριση πεζών/κεφαλαίων).'},example:'solve("level") → true',hint:{en:'Compare the string against its reverse.',el:'Σύγκρινε το κείμενο με την αντίστροφή του.'},starter:'function solve(text) {\n  // Your code here\n}',tests:[{args:['level'],expected:true},{args:['hello'],expected:false},{args:['a'],expected:true}]},
{id:'fizzbuzz',title:'FizzBuzz',level:'Medium',category:'Loops',description:{en:'Return "FizzBuzz" for numbers divisible by 15, "Fizz" for 3, "Buzz" for 5, otherwise return the number as a string.',el:'Επίστρεψε "FizzBuzz" για πολλαπλάσια του 15, "Fizz" για 3, "Buzz" για 5, διαφορετικά τον αριθμό ως κείμενο.'},example:'solve(15) → "FizzBuzz"',hint:{en:'Check divisibility by 15 first.',el:'Έλεγξε πρώτα τη διαιρετότητα με το 15.'},starter:'function solve(n) {\n  // Your code here\n}',tests:[{args:[15],expected:'FizzBuzz'},{args:[9],expected:'Fizz'},{args:[10],expected:'Buzz'},{args:[7],expected:'7'}]},
{id:'unique-values',title:'Unique Values',level:'Medium',category:'Arrays',description:{en:'Return an array without duplicate values, preserving original order.',el:'Επίστρεψε πίνακα χωρίς διπλότυπα, κρατώντας την αρχική σειρά.'},example:'solve([1, 2, 1, 3]) → [1, 2, 3]',hint:{en:'A Set preserves insertion order.',el:'Το Set διατηρεί τη σειρά εισαγωγής.'},starter:'function solve(nums) {\n  // Your code here\n}',tests:[{args:[[1,2,1,3]],expected:[1,2,3]},{args:[[]],expected:[]},{args:[[5,5,5]],expected:[5]}]},
{id:'two-sum',title:'Two Sum',level:'Medium',category:'Hash Maps',description:{en:'Given an integer array and target, return two distinct indices whose values sum to target. Exactly one solution exists.',el:'Για πίνακα αριθμών και στόχο, επέστρεψε δύο διαφορετικούς δείκτες των οποίων οι τιμές αθροίζονται στον στόχο. Υπάρχει μία λύση.'},example:'solve([2, 7, 11, 15], 9) → [0, 1]',hint:{en:'Store previously encountered values in a Map.',el:'Κράτησε προηγούμενες τιμές σε Map.'},starter:'function solve(nums, target) {\n  // Your code here\n}',tests:[{args:[[2,7,11,15],9],expected:[0,1]},{args:[[3,2,4],6],expected:[1,2]},{args:[[3,3],6],expected:[0,1]}]},
{id:'balanced',title:'Balanced Brackets',level:'Hard',category:'Stacks',description:{en:'Return true if (), [] and {} brackets are correctly balanced.',el:'Επίστρεψε true αν οι παρενθέσεις (), [] και {} είναι σωστά ισορροπημένες.'},example:'solve("([])") → true',hint:{en:'Use a stack for open brackets.',el:'Χρησιμοποίησε στοίβα για τα ανοίγματα.'},starter:'function solve(text) {\n  // Your code here\n}',tests:[{args:['([])'],expected:true},{args:['([)]'],expected:false},{args:[''],expected:true},{args:['(()'],expected:false}]}
]
